version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: blogapi:latest
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./blogsite/.env
    environment:
      - DJANGO_SETTINGS_MODULE=blogsite.settings
      - POSTGRES_PASSWORD=akbota
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akbota
